### model
model_name_or_path: D:\Pretrained_models\Qwen\Qwen2-1___5B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora #具体微调方法采用lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.2
lora_target: all

### dataset 数据集配置
dataset: anti_fraud
template: qwen
cutoff_len: 2048
max_samples: 500
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./Qwen2-1___5B-Instruct_ft_0213_17_55
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 100
